### ISSUE TITLE
Meds is medical confidence secret

### ISSUE THREAD

**Issue by Ygarr** [CorruptedArk/did-i-take-my-meds#38]
...to share it with not always a reliable device. So how about to rename to "Did I did smth in certain time" or so?

**Comment by CorruptedArk** [comment]
This app is specifically designed for medications, though. Additionally, you don't have to list your medications with their correct names if you don't want to. Also, the app doesn't send your information anywhere off of your device. Lastly, changing the name of the app doesn't change what kind of data it is designed to handle.

**Comment by caos30** [comment]
@Ygarr , when i want to increase at maximum the privacy managed by an android app i take this measures in my device:

- block the access by CODE/FINGERPRINT
- set as BORROW the "thumbnail" of the app when the user activate the view with all the opened apps 
- disable notifications on blocked screen
- remove from normal notifications (unblocked screen) all except title and logo of the app

Although in this case, the last point could be a little uncomfortable, because -at least me- i find very useful to be able to click on the menu inside those notifications ("Took it" and "Remind me in 15 minutes").

I hope you find interesting those suggestions :smile:
