### ISSUE TITLE
Allow multiple doses in the same time frame as an option

### ISSUE THREAD

**Issue by auctumnus** [CorruptedArk/did-i-take-my-meds#48]
**Is your feature request related to a problem? Please describe.**
A medication I take allows for either a split dose (once in the morning, once at night) or taking 2 doses at once. If I know I won't be home to take the dose in a split fashion, I'll do two at once, since it still works, but I don't have a way to record this in the app. If I try to press the "I just took it!" button twice, a notification pops up saying "I hope you didn't take it again!" instead of just letting me record this.

**Describe the solution you'd like**
An option to enable this for specific medications would work well. It wouldn't be breaking for anyone who depends on the current functionality since it would be opt-in.

**Describe alternatives you've considered**
It's possible to go without this but it can be difficult to remember which I did.

**Comment by EmperorArthur** [comment]
I am experiencing issues related to this as well.

For example, if I take a daily dose at night because I forgot to take it in the morning, then I can not record having taken it the next day!

This means that I cannot record my daily dose!

The entire "Hope you haven't taken it again" is not helpful.  It prevents me from recording doses, and I worry that I may accidentally overdose thanks to this app!

**Comment by CorruptedArk** [comment]
Yeah, this is a good change to make and it's at the top of my list for changes, I've just unfortunately been very busy lately
